---
- name: Setup NATS
  become: true  
  block:
    - name: Remove apt lock files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/var/lib/apt/lists/lock"
        - "/var/cache/apt/archives/lock"
        - "/var/lib/dpkg/lock"

    - name: Update and install required packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
        cache_valid_time: 3600
      vars:
        packages:
          - wget
          - gnupg
          - gnupg2

    - name: Ensure NATS user and directories
      block:
        - user:
            name: nats
            system: yes
            create_home: no
        - file:
            path: "{{ item }}"
            state: directory
            owner: nats
          loop:
            - /etc/nats
            - /var/log/nats
        - command: chown nats:nats /var/log/nats

    - name: Download and Install NATS
      block:
        - get_url:
            url: "https://github.com/nats-io/nats-server/releases/download/v2.10.1/nats-server-v2.10.1-amd64.deb"
            dest: "/tmp/nats-server.deb"
        - command: dpkg -i /tmp/nats-server.deb
      when: check_nats.rc != 0

    - name: Configure NATS for clustering
      template:
        src: nats.conf.j2
        dest: /etc/nats/nats.conf
        owner: nats
        mode: '0644'
      notify: 
        - Reload systemd
        - Restart NATS
    
    - name: Deploy NATS Systemd service file
      copy:
        src: nats-server.service
        dest: /etc/systemd/system/nats-server.service
        owner: root
        group: root
        mode: '0644'
      notify: 
        - Reload systemd
        - Restart NATS

  always:
    - name: Reload Systemd
      command: systemctl daemon-reload

    - name: Check NATS service status
      command: systemctl status nats-server
      register: nats_status
      changed_when: false
      failed_when: false
      when: nats_status.rc != 0

    - name: Clean-up for Debian/Ubuntu
      apt:
        autoremove: yes
        autoclean: yes
      when: ansible_facts['os_family'] == "Debian"
